// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdhfqauarqljqexflqtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkaGZxYXVhcnFsanFleGZscXR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5NzY5MDMsImV4cCI6MjA4NDU1MjkwM30.hFlN-cWrUIe7v_y0QQmrwMDAnAWT9u9knI9UQ6FmDTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
